name: Docker Compose Update

on:
  repository_dispatch:
    types: [docker-compose-update]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          echo Add your actions here